---
- hosts: all
  sudo: yes
  vars:

  tasks:

  - name: Postgresql | copy sql dump into the server
    copy: src={{ item.1.dump_sql }} dest=/tmp/{{ item.1.name }}.sql
    with_subelements:
    - postgresql_databases
    - databases
    when: item.1.dump_sql is defined

  - name: Postgresql | create database user
    postgresql_user: name={{ item.user }} password={{ item.password }}
    sudo_user: "{{postgresql_admin_user}}"
    with_items: postgresql_databases

  - name: Postgresql | create databases
    postgresql_db: name={{ item.1.name }}
    sudo_user: "{{postgresql_admin_user}}"
    with_subelements:
    - postgresql_databases
    - databases
    notify:
    - Postgresql | import sql dump


  - name: Postgresql | assign privileges to user
    postgresql_privs: >
      db={{ item.1.name }}
      privs=ALL
      type=database
      role={{ item.0.user }}
    sudo_user: "{{postgresql_admin_user}}"
    with_subelements:
    - postgresql_databases
    - databases

  - name: Server | Configure user for ssh connection
    user: name={{ item.user }} password="{{ item.password | password_hash('sha512') }}" shell=/bin/bash createhome=yes
    with_items: postgresql_databases

  handlers:

  - name: Postgresql | import sql dump
    shell: psql {{ item.1.name }} < /tmp/{{ item.1.name }}.sql
    sudo_user: "{{postgresql_admin_user}}"
    with_subelements:
    - postgresql_databases
    - databases
    when: item.1.dump_sql is defined
