---
- hosts: infra
  become: yes
  become_method: sudo
  vars:

  tasks:

  - name: Apt | Ensure OS is up to date
    apt: upgrade=safe

  - name: Apt | Ensure general packages are installed
    apt: name={{ item }} state=present
    with_items:
    - git
    - openjdk-7-jdk
    - maven

  - name: Apt | Ensure postgresql is installed
    apt: name={{ item }} state=present
    with_items:
    - postgresql-9.3
    - libpq-dev
    - python-psycopg2

  - name: Apt | Ensure postgis is installed
    apt: name={{ item }} state=present force=yes
    with_items:
    - postgresql-9.3-postgis-2.1
    - osm2pgsql
