---
- hosts: all
  sudo: yes
  vars:

  tasks:

  - name: Postgresql | deploy sportsdb dump
    copy: src={{inventory_dir}}/files/sportsdb_sample_postgresql_20080304.sql dest=/tmp/sportsdb.sql

  - name: Postgresql | create sportsdb
    postgresql_user: name={{ item.user }} db={{ item.database }} password={{ item.password }}
    sudo_user: "{{postgresql_admin_user}}"
    with_items: postgresql_sportsdb
    notify:
    - Postgresql | import sportsdb

  - name: Server | Configure user for ssh connection
    user: name={{ item.user }} password="{{ item.password | password_hash('sha512') }}" shell=/bin/bash createhome=yes 
    with_items: postgresql_sportsdb

  handlers:

  - name: Postgresql | import sportsdb
    shell: psql {{ item.database }} < /tmp/sportsdb.sql
    sudo_user: "{{postgresql_admin_user}}"
    with_items: postgresql_sportsdb
